# Default values for helm-flux2.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
